from __future__ import annotations

from typing import Any

from aqt.operations import CollectionOp
from aqt.qt import (
    QApplication,
    QDialog,
    QHBoxLayout,
    QLabel,
    QPlainTextEdit,
    QPushButton,
    QVBoxLayout,
)
from aqt.utils import showWarning, tooltip

from addon.errors import BundleError
from addon.example_data import EXAMPLE_BUNDLE_TEXT, LLM_GENERATION_GUIDANCE
from addon.importer import ImportSummary, import_bundle
from addon.service import bundle_from_text, summarize_bundle


class PasteCardsDialog(QDialog):
    def __init__(self, addcards: Any) -> None:
        super().__init__(addcards)
        self._addcards = addcards
        self._bundle = None
        self.setWindowTitle("Paste LLM Cards")
        self.resize(780, 620)
        self._setup_ui()

    def _setup_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(14, 14, 14, 14)
        layout.setSpacing(10)

        intro = QLabel(
            "Paste raw JSON or a fenced ```json / ```jsonc block generated by an LLM. "
            "The add-on will validate it, optionally create or update a note type, "
            "and add the notes directly into the deck currently selected in Add Cards. "
            "If your bundle omits note_type, make sure Add Cards is set to a working "
            "note type such as Basic before importing."
        )
        intro.setWordWrap(True)
        layout.addWidget(intro)

        guidance = QLabel(LLM_GENERATION_GUIDANCE)
        guidance.setWordWrap(True)
        layout.addWidget(guidance)

        self.bundle_input = QPlainTextEdit(self)
        self.bundle_input.setPlaceholderText(EXAMPLE_BUNDLE_TEXT)
        self.bundle_input.textChanged.connect(self._on_text_changed)
        layout.addWidget(self.bundle_input, 1)

        self.status_label = QLabel("Paste a bundle, then import it.")
        self.status_label.setWordWrap(True)
        layout.addWidget(self.status_label)

        buttons = QHBoxLayout()
        buttons.setSpacing(8)
        layout.addLayout(buttons)

        self.example_button = QPushButton("Copy Format Example", self)
        self.example_button.clicked.connect(self._copy_example)
        buttons.addWidget(self.example_button)

        buttons.addStretch(1)

        self.import_button = QPushButton("Import Cards", self)
        self.import_button.setDefault(True)
        self.import_button.clicked.connect(self._import_cards)
        buttons.addWidget(self.import_button)

        self.cancel_button = QPushButton("Cancel", self)
        self.cancel_button.clicked.connect(self.reject)
        buttons.addWidget(self.cancel_button)

    def _on_text_changed(self) -> None:
        self._bundle = None
        self.status_label.setText("Bundle changed. Import to validate and continue.")

    def _copy_example(self) -> None:
        QApplication.clipboard().setText(EXAMPLE_BUNDLE_TEXT)
        tooltip("Format example copied to clipboard.", period=2500)
        self.status_label.setText(
            "Format example copied to clipboard. Paste it into another LLM or edit it here."
        )

    def _parse_current_bundle(self):
        try:
            bundle = bundle_from_text(self.bundle_input.toPlainText())
        except BundleError as exc:
            showWarning(str(exc), parent=self)
            self.status_label.setText("Validation failed. Fix the bundle and try again.")
            return None

        self._bundle = bundle
        self.status_label.setText(summarize_bundle(bundle))
        return bundle

    def _import_cards(self) -> None:
        bundle = self._bundle or self._parse_current_bundle()
        if bundle is None:
            return

        from anki.collection import AddNoteRequest

        selected_deck_id = self._addcards.deck_chooser.selected_deck_id
        selected_notetype_id = self._addcards.notetype_chooser.selected_notetype_id

        self._set_busy(True)

        CollectionOp(
            self,
            lambda col: import_bundle(
                collection=col,
                bundle=bundle,
                selected_notetype_id=selected_notetype_id,
                selected_deck_id=selected_deck_id,
                request_factory=AddNoteRequest,
            ),
        ).success(self._on_import_success).failure(self._on_import_failure).run_in_background(
            initiator=self
        )

    def _on_import_success(self, summary: ImportSummary) -> None:
        self._set_busy(False)
        self.status_label.setText(self._success_message(summary))
        tooltip(self._success_message(summary), period=4000)
        self.accept()

    def _on_import_failure(self, error: Exception) -> None:
        self._set_busy(False)
        showWarning(str(error), parent=self)
        self.status_label.setText("Import failed. Review the error and try again.")

    def _set_busy(self, is_busy: bool) -> None:
        self.bundle_input.setEnabled(not is_busy)
        self.example_button.setEnabled(not is_busy)
        self.import_button.setEnabled(not is_busy)
        self.cancel_button.setEnabled(not is_busy)

    def _success_message(self, summary: ImportSummary) -> str:
        note_word = "note" if summary.note_count == 1 else "notes"
        message = f"Added {summary.note_count} {note_word} from the pasted bundle."
        if summary.created_note_type:
            return (
                f"{message} Created note type '{summary.note_type_name}'. "
                "Anki may request a full sync because the note type changed."
            )
        if summary.updated_note_type:
            return (
                f"{message} Updated note type '{summary.note_type_name}'. "
                "Anki may request a full sync because the note type changed."
            )
        return message
