from __future__ import annotations

from typing import Any

from aqt.operations import CollectionOp
from aqt.qt import (
    QDialog,
    QHBoxLayout,
    QLabel,
    QPlainTextEdit,
    QPushButton,
    QVBoxLayout,
)
from aqt.utils import showWarning, tooltip

from addon.errors import BundleError
from addon.importer import ImportSummary, import_bundle
from addon.service import bundle_from_text, summarize_bundle


_EXAMPLE_BUNDLE = """{
  "version": 1,
  "note_type": {
    "name": "Beautiful Basic",
    "fields": ["Front", "Back", "Extra"],
    "templates": [
      {
        "name": "Card 1",
        "qfmt": "<section class='hero'>{{Front}}</section>",
        "afmt": "{{FrontSide}}<hr id='answer'><section class='answer'>{{Back}}</section>{{#Extra}}<aside>{{Extra}}</aside>{{/Extra}}"
      }
    ],
    "css": ".card { font-family: 'Georgia'; background: linear-gradient(180deg, #fffdf8, #f4efe1); color: #1f2933; }"
  },
  "notes": [
    {
      "fields": {
        "Front": "<h1>What is the capital of Japan?</h1>",
        "Back": "<p>Tokyo</p>",
        "Extra": "<p>Population: about 14 million in the city proper.</p>"
      },
      "tags": ["llm", "geography"]
    }
  ]
}"""


class PasteCardsDialog(QDialog):
    def __init__(self, addcards: Any) -> None:
        super().__init__(addcards)
        self._addcards = addcards
        self._bundle = None
        self.setWindowTitle("Paste LLM Cards")
        self.resize(780, 620)
        self._setup_ui()

    def _setup_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(14, 14, 14, 14)
        layout.setSpacing(10)

        intro = QLabel(
            "Paste raw JSON or a fenced ```json block generated by an LLM. "
            "The add-on will validate it, optionally create or update a note type, "
            "and add the notes directly into the deck currently selected in Add Cards."
        )
        intro.setWordWrap(True)
        layout.addWidget(intro)

        self.bundle_input = QPlainTextEdit(self)
        self.bundle_input.setPlaceholderText(_EXAMPLE_BUNDLE)
        self.bundle_input.textChanged.connect(self._on_text_changed)
        layout.addWidget(self.bundle_input, 1)

        self.status_label = QLabel("Paste a bundle, then validate or import it.")
        self.status_label.setWordWrap(True)
        layout.addWidget(self.status_label)

        buttons = QHBoxLayout()
        buttons.setSpacing(8)
        layout.addLayout(buttons)

        self.example_button = QPushButton("Load Example", self)
        self.example_button.clicked.connect(self._load_example)
        buttons.addWidget(self.example_button)

        self.validate_button = QPushButton("Validate", self)
        self.validate_button.clicked.connect(self._validate_bundle)
        buttons.addWidget(self.validate_button)

        buttons.addStretch(1)

        self.import_button = QPushButton("Import Cards", self)
        self.import_button.setDefault(True)
        self.import_button.clicked.connect(self._import_cards)
        buttons.addWidget(self.import_button)

        self.cancel_button = QPushButton("Cancel", self)
        self.cancel_button.clicked.connect(self.reject)
        buttons.addWidget(self.cancel_button)

    def _on_text_changed(self) -> None:
        self._bundle = None
        self.status_label.setText("Bundle changed. Validate or import to continue.")

    def _load_example(self) -> None:
        self.bundle_input.setPlainText(_EXAMPLE_BUNDLE)

    def _validate_bundle(self) -> None:
        bundle = self._parse_current_bundle()
        if bundle is None:
            return
        self.status_label.setText(summarize_bundle(bundle))

    def _parse_current_bundle(self):
        try:
            bundle = bundle_from_text(self.bundle_input.toPlainText())
        except BundleError as exc:
            showWarning(str(exc), parent=self)
            self.status_label.setText("Validation failed. Fix the bundle and try again.")
            return None

        self._bundle = bundle
        return bundle

    def _import_cards(self) -> None:
        bundle = self._bundle or self._parse_current_bundle()
        if bundle is None:
            return

        from anki.collection import AddNoteRequest

        selected_deck_id = self._addcards.deck_chooser.selected_deck_id
        selected_notetype_id = self._addcards.notetype_chooser.selected_notetype_id

        self._set_busy(True)

        CollectionOp(
            self,
            lambda col: import_bundle(
                collection=col,
                bundle=bundle,
                selected_notetype_id=selected_notetype_id,
                selected_deck_id=selected_deck_id,
                request_factory=AddNoteRequest,
            ),
        ).success(self._on_import_success).failure(self._on_import_failure).run_in_background(
            initiator=self
        )

    def _on_import_success(self, summary: ImportSummary) -> None:
        self._set_busy(False)
        self.status_label.setText(self._success_message(summary))
        tooltip(self._success_message(summary), period=4000)
        self.accept()

    def _on_import_failure(self, error: Exception) -> None:
        self._set_busy(False)
        showWarning(str(error), parent=self)
        self.status_label.setText("Import failed. Review the error and try again.")

    def _set_busy(self, is_busy: bool) -> None:
        self.bundle_input.setEnabled(not is_busy)
        self.example_button.setEnabled(not is_busy)
        self.validate_button.setEnabled(not is_busy)
        self.import_button.setEnabled(not is_busy)
        self.cancel_button.setEnabled(not is_busy)

    def _success_message(self, summary: ImportSummary) -> str:
        note_word = "note" if summary.note_count == 1 else "notes"
        message = f"Added {summary.note_count} {note_word} from the pasted bundle."
        if summary.created_note_type:
            return f"{message} Created note type '{summary.note_type_name}'."
        if summary.updated_note_type:
            return f"{message} Updated note type '{summary.note_type_name}'."
        return message
